src/Entity/Trick.php
<?php

namespace App\Entity;

use App\Repository\TrickRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: TrickRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[UniqueEntity('title')]
#[Assert\Cascade]
class Trick implements EntitySlugInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\NotBlank]
    #[ORM\Column(length: 255, unique: true)]
    private ?string $title = null;

    #[ORM\Column(length: 255, unique: true)]
    private ?string $slug = null;

    #[Assert\Length(min: 10)]
    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $editedAt = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
    private ?User $author = null;

    #[Assert\NotBlank]
    #[ORM\ManyToOne(inversedBy: 'tricks')]
    #[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
    private ?Category $category = null;

    #[ORM\Column]
    private ?bool $valided = null;

    #[ORM\Column]
    private ?bool $published = null;

    #[Assert\Valid]
    #[Assert\Count(
        min: 1,
        max: 4,
        minMessage: 'Vous devez ajouter au moins {{ limit }} image.',
        maxMessage: 'Vous ne pouvez pas ajouter plus de {{ limit }} images.'
    )]
    #[ORM\OneToMany(mappedBy: 'trick', targetEntity: Image::class, cascade: ['persist', 'remove'])]
    private Collection $images;

    #[ORM\OneToMany(mappedBy: 'trick', targetEntity: Video::class, orphanRemoval: true, cascade: ['persist', 'remove'])]
    private Collection $videos;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->videos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getEditedAt(): ?\DateTimeImmutable
    {
        return $this->editedAt;
    }

    public function setEditedAt(\DateTimeImmutable $editedAt): self
    {
        $this->editedAt = $editedAt;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function isValided(): ?bool
    {
        return $this->valided;
    }

    public function setValided(bool $valided): self
    {
        $this->valided = $valided;

        return $this;
    }

    public function isPublished(): ?bool
    {
        return $this->published;
    }

    public function setPublished(bool $published): self
    {
        $this->published = $published;

        return $this;
    }

    #[ORM\PrePersist]
    public function setValueWhenPersist(): void
    {
        $this->createdAt = new \DateTimeImmutable();
        $this->editedAt = new \DateTimeImmutable();
        $this->published = true;
    }

    #[ORM\PreUpdate]
    public function setValueWhenUpdate(): void
    {
        $this->editedAt = new \DateTimeImmutable();
    }

    public function targetField(): string
    {
        return 'title';
    }

    public function __toString()
    {
        return $this->title; /* @phpstan-ignore-line */
    }

    /**
     * @return Collection<int, Image>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setTrick($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getTrick() === $this) {
                $image->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Video>
     */
    public function getVideos(): Collection
    {
        return $this->videos;
    }

    public function addVideo(Video $video): self
    {
        if (!$this->videos->contains($video)) {
            $this->videos->add($video);
            $video->setTrick($this);
        }

        return $this;
    }

    public function removeVideo(Video $video): self
    {
        if ($this->videos->removeElement($video)) {
            // set the owning side to null (unless already changed)
            if ($video->getTrick() === $this) {
                $video->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * getFeatured.
     */
    public function getFeatured(): Image|false
    {
        return $this->getImages()->first();
    }
    
    /**
     * getGallery
     *
     * @return array<mixed>
     */
    public function getGallery(): array
    {
        $this->getImages()->remove(0);

        return array_merge($this->getImages()->toArray(), $this->getVideos()->toArray());
    }
}

templates/components/alert.html.twig
<div{{ attributes }}>
    <div class="{{ html_classes("alert alert-"~type, {
        "alert-dismissible fade show": dismissible
    }) }}" role="alert">
        {{ message }}
        {% if dismissible %}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        {% endif %}
    </div>
</div>

templates/components/card_comment.html.twig
<div{{ attributes }}>
    <div data-live-id={{ comment.id }} class="col-12">
        <header class="py-2 border-bottom d-flex align-items-center">
            <span>
                {{ avatar(comment.author) }}
            </span>

            <div class="ms-3">
                <span class="fw-bold d-block">{{ comment.author.username }}</span>
                <span class="small d-block">{{ comment.createdAt | date('d/m/Y h:i') }}</span>
            </div>
        </header>

        <div class="mt-2">
            {{ comment.content | raw }}
        </div>

        {% if is_granted('IS_AUTHENTICATED_FULLY') %}
            <footer class="d-flex justify-content-end align-items-center">
                {% if is_granted('COMMENT_ACCESS', comment) %}
                    <a  class="link-info d-inline-block" 
                        data-bs-toggle="collapse" 
                        data-bs-target="#collapseEditComment{{ comment.id }}"
                        role="button" 
                        aria-expanded="false" 
                        aria-controls="collapseEditComment{{ comment.id }}">
                            <i class="bi bi-pencil-square h5"></i>
                    

                    <div class="dropdown">
                        <a title="supprimer" class="dropdown-toggle mx-2 link-danger" href="#" type="button" data-bs-toggle="dropdown" aria-expanded="false">
                            <i class="bi bi-trash3 h5"></i>
                        </a>

                        <ul class="dropdown-menu border p-3" style="width: 250px">
                            <p>Voulez-vous supprimer ce commentaire ?</p>
                            <button class="btn btn-danger btn-sm scale"
                                    data-action="live#action"
                                    data-action-name="removeComment(id={{ comment.id }})">Supprimer
                            </button>
                        </ul>
                    </div>
                {% endif %}
            </footer>

            <div class="collapse mt-3" id="collapseEditComment{{ comment.id }}">
                {{ form_start(form) }}
                    {{ form_row(form.content) }}
                    <button type="button"
                        data-action="live#action"
                        data-action-name="editComment(id={{ comment.id }})"
                        class="btn btn-sm scale btn-info">Modifier
                        <div    data-loading="action(editComment)|show"
                                class="ms-3 spinner-border spinner-border-sm" 
                                role="status">
                                <span class="visually-hidden">Loading</span>
                        </div>
                    </button>
                {{ form_end(form) }}
            </div>
        {% endif %}
    </div>
</div>

templates/components/card_trick.html.twig
<div{{ attributes.defaults({ class: 'col-12' }) }}>

    <article class="d-md-flex">
        <div class="col-md-3 flex-shrink-0">
            <img class="img-fluid scale" src="{{ asset("/images/trick/" ~ trick.featured.path) }}" alt="{{ trick.featured.alt }}">
        </div>

        <div class="flex-grow-1 ms-md-4">
            <header class="my-3 mt-md-0 mb-md-2 d-xl-flex justify-content-between align-item-center">
                <h4 class="mb-0 h5 fw-bold">{{ trick.title }}</h4>
                <span class="text-small">{{ trick.createdAt | date('d/m/Y') }}</span>
            </header>

            <div>
                <p class="mb-1 fst-italic">{{ trick.category.name }}</p>
                <p>{{ trick.content |u.truncate(100, ' ...', false) | raw }}</p>
                <p>
                    <a href="{{ path('trick.show', {slug: trick.slug}) }}" class="btn btn-action scale btn-sm shadow-sm">Lire la suite</a>
                </p>
            </div>
        </div>
    
    </article>
</div>

templates/components/comment.html.twig
<div{{ attributes.defaults({ class: 'mt-5' }) }}>

    <header class="mb-4">
        <h4 class="h5 fw-bold">{{ plurial(this.count, 'Commentaire', 'Commentaires') }} ({{ this.count }})</h4>
    </header>

    {% if not is_granted('IS_AUTHENTICATED_FULLY') %}
        <section class="bg-light p-3 mb-4 fw-bold">
            <p>Pour ajouter un commentaire, vous devez être connecté</p>
            <p class="mb-0">
                <a class="btn btn-action scale" href="{{ path('app_login') }}">Connexion</a>
            </p>
        </section>
    {% endif %}

    <div class="row g-5 mb-4">
        {% for key, comment in computed.comments %}
            {{ component('card_comment', {
                'comment': comment,
                'key': comment.id,
            }) }}
        {% endfor %}
    </div>

    {% if this.showButton %}
    <button class="btn btn-outline-primary scale"
            data-action-name="increment()"
            data-action="live#action">Plus de commentaires
            
        <div    data-loading="action(increment)|show"
                class="ms-3 spinner-border spinner-border-sm" 
                role="status">
            <span class="visually-hidden">Loading</span>
        </div>
        
    </button>
    {% endif %}

    {% if is_granted('IS_AUTHENTICATED_FULLY') %}
        <div class="mt-4">
            {{ form_start(form) }}
                {{ form_row(form.content) }}
                <button type="button"
                        data-action="live#action"
                        data-action-name="addComment"
                        class="btn btn-sm btn-primary scale">Poster
                            <div    data-loading="action(addComment)|show"
                                    class="ms-3 spinner-border spinner-border-sm" 
                                    role="status">
                                <span class="visually-hidden">Loading</span>
                            </div>
                </button>
            {{ form_end(form) }}
        </div>
    {% endif %}
</div>

templates/components/toast.html.twig
<div{{ attributes.defaults({class: "toast-container position-fixed top-0 end-0 p-3", style: "z-index: 500"}) }}>
    <div id="liveToast" class="toast show text-bg-{{ type }} p-2" role="alert" aria-live="assertive" aria-atomic="true">
        <div class="d-flex align-items-center justify-content-between">
            <div class="toast-body">
                {{ message }}
            </div>
            <button type="button" class="btn-close me-2" data-bs-dismiss="toast" aria-label="Close"></button>
        </div>
    </div>
</div>

templates/components/trick_list.html.twig
<div{{ attributes }}>
    
    <div class="row g-5 mb-4" data-model="on(change)|tricks">
        {% if this.tricks is empty %}
            <p>Aucunes figures enregistrées.</p>
        {% endif %}

        {% for trick in this.tricks %}
            {{ component('card_trick', {
                'trick': trick,
            }) }}
        {% endfor %}
    </div>

    {% if this.showButton %}
        <button class="btn btn-outline-primary scale"
                data-action-name="increment()"
                data-action="live#action">Plus de figures
                
            <div    data-loading 
                    class="ms-3 spinner-border spinner-border-sm" 
                    role="status">
                <span class="visually-hidden">Loading</span>
            </div>
            
        </button>
    {% endif %}

</div>

templates/components/trick_list_and_search.html.twig
<div{{ attributes }}>

    <header class="mb-5">
        <div class="mb-3 col-lg-6 col-xl-4">
            <label class="form-label">Rechercher</label>
            <input  type="search" 
                    data-model="query" 
                    class="form-control scale"
                    value="{{ query }}" 
                    data-model="debounce(500)|query">
        </div>

        <div>
            <p class="mb-1 fw-bold">Catégories</p>
            <div class="overflow-auto d-flex gap-2 pb-3">
                <button data-action="live#action"
                        data-action-name="setCategoryName(categoryName=all)"
                        class="{{ html_classes('px-3 py-1 border-0', {
                            "bg-primary text-white": categoryName == "all",
                            "bg-white": categoryName != "all"
                        }) }}">All</button>

                {% for category in this.categories %}
                    <button     data-action="live#action"
                                data-action-name="setCategoryName(categoryName={{ category.name }})"

                                class="{{ html_classes('px-3 py-1 border-0', {
                                    "bg-primary text-white": categoryName == category.name,
                                    "bg-white": categoryName != category.name
                                }) }}">{{ category.name }}</button>
                {% endfor %}

            </div>
        </div>
    </header>

    <section class="row g-5 mb-4 overflow-hidden">
        {% if this.tricks is empty %}
            <p>Aucunes figures enregistrées.</p>
        {% endif %}
        
        {% for trick in this.tricks %}
            {{ component('card_trick', {
                'trick': trick
            }) }}
        {% endfor %}
    </section>

    {% if this.showButton and query is empty %}
    <button class="btn btn-outline-primary scale"
            data-action-name="increment()"
            data-action="live#action">Plus de figures
            
        <div    data-loading 
                class="ms-3 spinner-border spinner-border-sm" 
                role="status">
            <span class="visually-hidden">Loading</span>
        </div>
        
    </button>
    {% endif %}
</div>