src/Entity/Trick.php
<?php

namespace App\Entity;

use App\Repository\TrickRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity;
use Symfony\Component\Validator\Constraints as Assert;

#[ORM\Entity(repositoryClass: TrickRepository::class)]
#[ORM\HasLifecycleCallbacks]
#[UniqueEntity('title')]
#[Assert\Cascade]
class Trick implements EntitySlugInterface
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[Assert\NotBlank]
    #[ORM\Column(length: 255, unique: true)]
    private ?string $title = null;

    #[ORM\Column(length: 255, unique: true)]
    private ?string $slug = null;

    #[Assert\Length(min: 10)]
    #[ORM\Column(type: Types::TEXT)]
    private ?string $content = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $createdAt = null;

    #[ORM\Column]
    private ?\DateTimeImmutable $editedAt = null;

    #[ORM\ManyToOne]
    #[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
    private ?User $author = null;

    #[Assert\NotBlank]
    #[ORM\ManyToOne(inversedBy: 'tricks')]
    #[ORM\JoinColumn(nullable: true, onDelete: 'SET NULL')]
    private ?Category $category = null;

    #[ORM\Column]
    private ?bool $valided = null;

    #[ORM\Column]
    private ?bool $published = null;

    #[Assert\Valid]
    #[Assert\Count(
        min: 1,
        max: 4,
        minMessage: 'Vous devez ajouter au moins {{ limit }} image.',
        maxMessage: 'Vous ne pouvez pas ajouter plus de {{ limit }} images.'
    )]
    #[ORM\OneToMany(mappedBy: 'trick', targetEntity: Image::class, cascade: ['persist', 'remove'])]
    private Collection $images;

    #[ORM\OneToMany(mappedBy: 'trick', targetEntity: Video::class, orphanRemoval: true, cascade: ['persist', 'remove'])]
    private Collection $videos;

    public function __construct()
    {
        $this->images = new ArrayCollection();
        $this->videos = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getSlug(): ?string
    {
        return $this->slug;
    }

    public function setSlug(string $slug): self
    {
        $this->slug = $slug;

        return $this;
    }

    public function getContent(): ?string
    {
        return $this->content;
    }

    public function setContent(string $content): self
    {
        $this->content = $content;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeImmutable
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeImmutable $createdAt): self
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getEditedAt(): ?\DateTimeImmutable
    {
        return $this->editedAt;
    }

    public function setEditedAt(\DateTimeImmutable $editedAt): self
    {
        $this->editedAt = $editedAt;

        return $this;
    }

    public function getAuthor(): ?User
    {
        return $this->author;
    }

    public function setAuthor(?User $author): self
    {
        $this->author = $author;

        return $this;
    }

    public function getCategory(): ?Category
    {
        return $this->category;
    }

    public function setCategory(?Category $category): self
    {
        $this->category = $category;

        return $this;
    }

    public function isValided(): ?bool
    {
        return $this->valided;
    }

    public function setValided(bool $valided): self
    {
        $this->valided = $valided;

        return $this;
    }

    public function isPublished(): ?bool
    {
        return $this->published;
    }

    public function setPublished(bool $published): self
    {
        $this->published = $published;

        return $this;
    }

    #[ORM\PrePersist]
    public function setValueWhenPersist(): void
    {
        $this->createdAt = new \DateTimeImmutable();
        $this->editedAt = new \DateTimeImmutable();
        $this->published = true;
    }

    #[ORM\PreUpdate]
    public function setValueWhenUpdate(): void
    {
        $this->editedAt = new \DateTimeImmutable();
    }

    public function targetField(): string
    {
        return 'title';
    }

    public function __toString()
    {
        return $this->title; /* @phpstan-ignore-line */
    }

    /**
     * @return Collection<int, Image>
     */
    public function getImages(): Collection
    {
        return $this->images;
    }

    public function addImage(Image $image): self
    {
        if (!$this->images->contains($image)) {
            $this->images->add($image);
            $image->setTrick($this);
        }

        return $this;
    }

    public function removeImage(Image $image): self
    {
        if ($this->images->removeElement($image)) {
            // set the owning side to null (unless already changed)
            if ($image->getTrick() === $this) {
                $image->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Video>
     */
    public function getVideos(): Collection
    {
        return $this->videos;
    }

    public function addVideo(Video $video): self
    {
        if (!$this->videos->contains($video)) {
            $this->videos->add($video);
            $video->setTrick($this);
        }

        return $this;
    }

    public function removeVideo(Video $video): self
    {
        if ($this->videos->removeElement($video)) {
            // set the owning side to null (unless already changed)
            if ($video->getTrick() === $this) {
                $video->setTrick(null);
            }
        }

        return $this;
    }

    /**
     * getFeatured.
     */
    public function getFeatured(): Image|false
    {
        return $this->getImages()->first();
    }
    
    /**
     * getGallery
     *
     * @return array<mixed>
     */
    public function getGallery(): array
    {
        $this->getImages()->remove(0);

        return array_merge($this->getImages()->toArray(), $this->getVideos()->toArray());
    }
}

src/Form/Trick/TrickType.php
<?php

namespace App\Form\Trick;

use App\Entity\Trick;
use App\Form\Comment\CommentType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\UX\LiveComponent\Form\Type\LiveCollectionType;

class TrickType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('comments', LiveCollectionType::class, [
                'entry_type' => CommentType::class,
                'label' => false,
            ])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Trick::class,
        ]);
    }
}

src/Controller/TrickController.php
<?php

namespace App\Controller;

use App\Entity\Trick;
use App\Repository\TrickRepository;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class TrickController extends AbstractController
{
    #[Route('/tricks', name: 'trick.list', methods: ['GET'])]
    public function index(): Response
    {
        return $this->render('trick/index.html.twig');
    }

    #[Route('/tricks/{slug}', name: 'trick.show', methods: ['GET'])]
    public function show(Trick $trick, TrickRepository $trickRepository): Response
    {
        if (!$trick->isValided() || !$trick->isPublished()) {
            throw $this->createNotFoundException();
        }

        /* @phpstan-ignore-next-line */
        $tricksSameCategory = $trickRepository->findByCategory($trick->getCategory(), $trick->getId());

        return $this->render('trick/show.html.twig', [
            'trick' => $trick,
            'tricksSameCategory' => $tricksSameCategory,
        ]);
    }
}

templates/trick/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Liste des figures{% endblock %}

{% block body %}
    <section>
        <header class="mb-4">
            <h2 class="mb-0 fw-bold">Liste des figures</h2>
        </header>
        {{ component('trick_list_and_search') }}
    </section>
{% endblock %}

templates/trick/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}{{ trick.title }}{% endblock %}

{% block body %}
    <section>
        <header class="mb-4">
            <p>Publié le {{ trick.createdAt | date('d/m/Y') }} 
                {% if trick.author is not null %}
                    par {{ trick.author.username }}
                {% endif %}    
            </p>
        </header>

        <div class="row g-4">
            <section class="{{
                html_classes("col-12", {
                    "col-lg-8": tricksSameCategory is not empty
                })
            }}">

                {% if trick.gallery is not empty %}
                    {% include "front/partials/_carousel.html.twig" %}
                {% endif %}

                {{ trick.content | raw }}

                {{ component('comment', {
                    'trick': trick,
                }) }}

            </section>

            {% if tricksSameCategory is not empty %}
                <aside class="col-12 col-lg-4">
                    {# Liste des figures de la même catégorie #}
                    <div>
                        <h3 class="h5 fw-bold">Dans la même catégorie</h3>
                        <ul class="list-group">
                            {% for t in tricksSameCategory %}
                                <li class="list-group-item">
                                    <a href="{{ path('trick.show', {slug: t.slug}) }}">{{ t.title }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                    {# Liste des figures de la même catégorie #}
                </aside>
            {% endif %}
        </div>

    </section>
{% endblock %}